baseURL = "https://jk-developing.github.io/jvkfotografie/"
title = "JVK Fotografie"
languageCode = "nl-NL"
defaultContentLanguage = "nl"
enableRobotsTXT = true
theme = "hugo-theme-gallery"
disableKinds = ["taxonomy"]
timeZone = "Europe/Amsterdam"
timeout = "120s"

[params]
  defaultTheme = "dark"
  description = "Portfolio van JVK Fotografie"
  title = "JVK Fotografie"
  [params.author]
    name = "jvkfotografie"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 85
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[services]
  [services.rss]
    limit = 100

[menu]
  [[menu.main]]
    name = "Natuur"
    url = "/natuur/"
    weight = 10
  [[menu.main]]
    name = "Portret"
    url = "/portret/"
    weight = 20
  [[menu.main]]
    name = "Architectuur"
    url = "/architectuur/"
    weight = 30
  [[menu.main]]
    name = "Over"
    url = "/about/"
    weight = 40
